FROM golang:1.11-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers

ADD . /vicion
RUN cd /vicion && make bootnode

RUN chmod +x /vicion/build/bin/bootnode

FROM alpine:latest

LABEL maintainer="etienne@vicion.com"

WORKDIR /vicion

COPY --from=builder /vicion/build/bin/bootnode /usr/local/bin/bootnode

COPY docker/bootnode ./

EXPOSE 30301

ENTRYPOINT ["./entrypoint.sh"]

CMD ["-verbosity", "6", "-nodekey", "bootnode.key", "--addr", ":30301"]
